### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gatemezing** [huanyu-li/Materials-Design-Ontology#2]
Is this https://github.com/huanyu-li/Materials-Design-Ontology/blob/master/LICENSE similar to https://opensource.org/licenses/MIT?

**Comment by rartino** [comment]
I'm not sure exactly what you are asking? As github correctly identify in the header in your first URL:  https://github.com/huanyu-li/Materials-Design-Ontology/blob/master/LICENSE , the data in this repository is under the MIT license, which is the license you link to. Just looking at the two texts should show that they are identical, except for the copyright line.
